---

# Puppet Classes to load and execute
classes:
  - applicationserver

# UNIX groups
group:
  dmadmin:
    ensure:     present
  tomcat:
    ensure:     present

# UNIX users
user:
  tomcat:
    ensure:     present
    managehome: true
    comment:    Tomcat Install Owner
    shell:      '/bin/bash'
    password:   "$1$uwPiRsox$GEe9mUGEav92rx4ooq6Nf." # vagrant
    gid:        tomcat
    groups:
                - dmadmin
                - wheel
    require:
                - Group[dmadmin]
                - Group[wheel]

# UNIX Packages
package:
  jdk:
    ensure:     1.7.0_79-fcs
    provider:   rpm
    source:     /opt/media/3rdParty/JDK/1.7/jdk-7u79-linux-x64.rpm

# UNIX folders and files
file:
  '/u02':
    ensure:     directory
  '/u02/app':
    ensure:     directory
  '/u02/app/apache-tomcat':
    ensure:     directory
    owner:      tomcat
    group:      tomcat
    mode:       '775'
  '/home/tomcat/apache-tomcat':
    ensure:     link
    owner:      tomcat
    group:      tomcat
    mode:       '775'
    target:     '/u02/app/apache-tomcat'


# Configure Tomcat
applicationserver::http_port:     7070
applicationserver::catalina_root: /u02/app/apache-tomcat
